gOtherText_NewName::
	.string "NEW NAME$"

gNameChoice_Green::
	.string "GREEN$"

gNameChoice_Red::
	.string "RED$"

gNameChoice_Leaf::
	.string "LEAF$"

gNameChoice_Fire::
	.string "FIRE$"

gNameChoice_Gary::
	.string "GARY$"

gNameChoice_Kaz::
	.string "KAZ$"

gNameChoice_Toru::
	.string "TORU$"

gNameChoice_Ash::
	.string "ASH$"

gNameChoice_Kene::
	.string "KENE$"

gNameChoice_Geki::
	.string "GEKI$"

gNameChoice_Jak::
	.string "JAK$"

gNameChoice_Janne::
	.string "JANNE$"

gNameChoice_Jonn::
	.string "JONN$"

gNameChoice_Kamon::
	.string "KAMON$"

gNameChoice_Karl::
	.string "KARL$"

gNameChoice_Taylor::
	.string "TAYLOR$"

gNameChoice_Oscar::
	.string "OSCAR$"

gNameChoice_Hiro::
	.string "HIRO$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALPH$"

gNameChoice_Kay::
	.string "KAY$"

gNameChoice_Tosh::
	.string "TOSH$"

gNameChoice_Roak::
	.string "ROAK$"

gNameChoice_Omi::
	.string "OMI$"

gNameChoice_Jodi::
	.string "JODI$"

gNameChoice_Amanda::
	.string "AMANDA$"

gNameChoice_Hillary::
	.string "HILLARY$"

gNameChoice_Makey::
	.string "MAKEY$"

gNameChoice_Michi::
	.string "MICHI$"

gNameChoice_Paula::
	.string "PAULA$"

gNameChoice_June::
	.string "JUNE$"

gNameChoice_Cassie::
	.string "CASSIE$"

gNameChoice_Rey::
	.string "REY$"

gNameChoice_Seda::
	.string "SEDA$"

gNameChoice_Kiko::
	.string "KIKO$"

gNameChoice_Mina::
	.string "MINA$"

gNameChoice_Norie::
	.string "NORIE$"

gNameChoice_Sai::
	.string "SAI$"

gNameChoice_Momo::
	.string "MOMO$"

gNameChoice_Suzi::
	.string "SUZI$"

gControlsGuide_Text_Intro::
	.string "Welcome to POKéMON FireRed: Doubles Edition!\n"
	.string "Developed by Prince Fluff$"

gControlsGuide_Text_DPad::
	.string "FRDE has several unique features\n"
	.string "beyond just being all-doubles.\n"
	.string "Check docs for all changes.$"

gControlsGuide_Text_AButton::
	.string "Route 3 (but not Mt. Moon) can be\n"
	.string "accessed with 0 Gym Badges.$"

gControlsGuide_Text_BButton::
	.string "Running Shoes are enabled from the\n"
	.string "start and can be used indoors.$"

gControlsGuide_Text_StartButton::
	.string "The TURN PREVIEW feature shows\n"
	.string "speed and target info in battle.$"

gControlsGuide_Text_SelectButton::
	.string "Press Select on the battle menu\n"
	.string "to access TURN PREVIEW.$"

gControlsGuide_Text_LRButtons::
	.string "Press L or R while selecting a move\n"
	.string "in battle to see opponent's moves.\n"
	.string "Press again to revert.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Now tell me. Will you be a boy?\n"
	.string "Or will you be a girl?$"

gPikachuIntro_Text_Page1::
	.string "In the world which you are about to\n"
	.string "enter, you will embark on a grand\n"
	.string "adventure with you as the hero.\n"
	.string "\n"
	.string "Speak to people and check things\n"
	.string "wherever you go, be it towns, roads,\n"
	.string "or caves. Gather information and\n"
	.string "hints from every source.$"

gPikachuIntro_Text_Page2::
	.string "New paths will open to you by helping\n"
	.string "people in need, overcoming challenges,\n"
	.string "and solving mysteries.\n"
	.string "\n"
	.string "At times, you will be challenged by\n"
	.string "others and attacked by wild creatures.\n"
	.string "Be brave and keep pushing on.$"

gPikachuIntro_Text_Page3::
	.string "Through your adventure, we hope\n"
	.string "that you will interact with all sorts\n"
	.string "of people and achieve personal growth.\n"
	.string "That is our biggest objective.\n"
	.string "\n"
	.string "Press the A Button, and let your\n"
	.string "adventure begin!$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Hello, there!\n"
	.string "Glad to meet you!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is OAK.\p"
	.string "People affectionately refer to me\n"
	.string "as the POKéMON PROFESSOR.\p$"

gOakSpeech_Text_ThisWorld::
	.string "This world…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "…is inhabited far and wide by\n"
	.string "creatures called POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "For some people, POKéMON are pets.\n"
	.string "Others use them for competition.\p"
	.string "As for myself…\p"
	.string "I study POKéMON as a profession.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "But first, tell me a little about\n"
	.string "yourself.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Let's begin with your name.\n"
	.string "What is it?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "Right…\n"
	.string "So your name is {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
	.string "This is my grandson.\p"
	.string "He's been your rival since you both\n"
	.string "were babies.\p"
	.string "…Erm, what was his name now?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "Your rival's name, what was it now?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "…Er, was it {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "That's right! I remember now!\n"
	.string "His name is {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
	.string "{PLAYER}!\p"
	.string "Your very own POKéMON legend is\n"
	.string "about to unfold!\p"
	.string "A world of dreams and adventures\n"
	.string "with POKéMON awaits! Let's go!$"
